---
title: "strings_and_factors"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
library(p8105.datasets)
library(stringr)
```

## Strings and regex

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")
```
```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")

str_detect(string_vec, "^i think")

str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "Bush")

str_detect(string_vec, "[Bb]ush")
```
```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```
```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
```
```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```

## Factors

```{r}
factor_vec=factor(c("male", "female", "female", "female"))

factor_vec

as.numeric(factor_vec)
```
What happens if I relevel...

```{r}
factor_vec= fct_relevel(factor_vec, "male")

factor_vec

as.numeric(factor_vec)
```

##NSDUH

```{r}
 url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html=read_html(url)

table_marj=
drug_use_html %>% 
  html_nodes(css="table") %>% 
  first() %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```

```{r}
data_marj=
  table_marj %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    -State,
    names_to= "age_year",
    values_to="percent",
  ) %>% 
  separate(age_year, into=c("age", "year"), sep = "\\(") %>% 
  mutate(
    year=str_replace(year, "\\)", ""),
    percent=str_replace(percent, "[a-c]$", ""),
    percent=as.numeric(percent)
  ) %>% 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```
## NSDUH-- factors

```{r}

data_marj %>% 
  filter(age== "12-17") %>% 
  mutate(State=fct_relevel(State,"Texas", "Oklahoma"))%>% 
  ggplot(aes(State, y=percent, color=year))+
  geom_point()+
  theme(axis.text.x= element_text(angle=90, vjust=90, hjust=1))

data_marj %>% 
  filter(age== "12-17") %>% 
  mutate(State=fct_reorder(State,percent))%>% 
  ggplot(aes(State, y=percent, color=year))+
  geom_point()+
  theme(axis.text.x= element_text(angle=90, vjust=90, hjust=1))
```
## Weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df %>% 
  mutate(name=fct_relevel(name, "Waikiki_HA")) %>% 
  ggplot(aes(x=name, y=tmax))+
  geom_violin()

weather_df %>% 
  mutate(name=fct_reorder(name, tmax)) %>% 
  ggplot(aes(x=name, y=tmax))+
  geom_violin()

```
```{r}
weather_df %>% 
  mutate(name= fct_reorder(name, tmax)) %>% 
  lm(tmax~name, data=.)
```

